<a href="https://colab.research.google.com/github/arddrasoni-commits/14_dataset_normalisation/blob/main/experiment_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 14
# Data Normalisation and Data Type Conversion
## Arddra Soni
## 25070123022
## ENTC A1

In [6]:
#Dataset
import pandas as pd
import numpy as np

data = {
    'product':['amplifier','jack','rosin','bridge'],
    'price':[10000,7000,9000,6000],
    'Units_sold':[20,30,70,50]

}

df = pd.DataFrame(data)
print(df)

     product  price  Units_sold
0  amplifier  10000          20
1       jack   7000          30
2      rosin   9000          70
3     bridge   6000          50

In [7]:
# 1. Min-Max Normalisation
# Min max normalisation for price

df['price_MinMax'] = (df['price'] - df['price'].min()) / (df['price'].max() - df['price'].min())

print('\nMin-Max Normalised price:\n')
print(df[['product','price','price_MinMax']])

Min-Max Normalised price:

     product  price  price_MinMax
0  amplifier  10000          1.00
1       jack   7000          0.25
2      rosin   9000          0.75
3     bridge   6000          0.00

In [8]:
#Normalise Multiple Columns
cols=['Price','Units_Sold','Discount']

df_norm=(df[cols]-df[cols].min())/(df[cols].max()-df[cols].min())

print("Normalized Dataset")
print(df_norm)

KeyError: "None of [Index(['Price', 'Units_Sold', 'Discount'], dtype='object')] are in the [columns]"

In [9]:
# 2. Z-Score normalisation
df['Units_sold_zscore'] = (df['Units_sold'] - df['Units_sold'].mean()) / df['Units_sold'].std()

print('\nZ-Score Normalised Units_sold:\n')
print(df[['product','Units_sold','Units_sold_zscore']])

Z-Score Normalised Units_sold:

     product  Units_sold  Units_sold_zscore
0  amplifier          20          -1.014722
1       jack          30          -0.563735
2      rosin          70           1.240216
3     bridge          50           0.338241

In [10]:
# 3. Decimal-Scaling
df['price_decimal'] = df['price'] / 100000

print('\nDecimal Scaled price:\n')
print(df[['product','price','price_decimal']])

Decimal Scaled price:

     product  price  price_decimal
0  amplifier  10000           0.10
1       jack   7000           0.07
2      rosin   9000           0.09
3     bridge   6000           0.06

# New Dataset Operations

In [11]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/amazon_products_dataset_Expt-14.csv')
df

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [12]:
# 1. Min-Max Normalisation
# Min max normalisation for price

df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

df['Rating_MinMax'] = (df['Rating'] - df['Rating'].min()) / (df['Rating'].max() - df['Rating'].min())

df['Reviews_MinMax'] = (df['Reviews'] - df['Reviews'].min()) / (df['Reviews'].max() - df['Reviews'].min())

print('\nMin-Max Normalised Price, Rating, Reviews:\n')
print(df[['Product_Name','Reviews','Reviews_MinMax','Rating','Rating_MinMax','Reviews','Reviews_MinMax']])

Min-Max Normalised Price, Rating, Reviews:

                   Product_Name  Reviews  Reviews_MinMax  Rating  \
0                Wireless Mouse     1520        0.291005     4.3
1             Bluetooth Speaker      980        0.148148     4.5
2                  USB Keyboard      870        0.119048     4.1
3                Gaming Headset     2100        0.444444     4.6
4                    Smartwatch     3050        0.695767     4.4
5                    Power Bank     1750        0.351852     4.2
6                  Laptop Stand      620        0.052910     4.0
7                        Webcam     1120        0.185185     4.3
8                  Portable SSD     1850        0.378307     4.7
9              Wireless Charger      760        0.089947     4.2
10  Noise Cancelling Headphones     4200        1.000000     4.6
11          Mechanical Keyboard     2100        0.444444     4.5
12                 Gaming Mouse     1300        0.232804     4.4
13                 Tablet Stand      540        0.031746     4.1
14                      USB Hub      870        0.119048     4.2
15          External Hard Drive     2300        0.497354     4.6
16            Smartphone Tripod      760        0.089947     4.3
17              Laptop Backpack     1600        0.312169     4.4
18            Bluetooth Earbuds     3500        0.814815     4.5
19                LED Desk Lamp      980        0.148148     4.3
20                 Phone Holder      420        0.000000     4.0
21            Wireless Keyboard     1450        0.272487     4.4
22             Portable Monitor     1250        0.219577     4.6
23                   Smart Plug      720        0.079365     4.2
24                  WiFi Router     2100        0.444444     4.5
25              Graphics Tablet      980        0.148148     4.4
26                   VR Headset     3100        0.708995     4.7
27                   Microphone     1300        0.232804     4.3
28             Smart Light Bulb      880        0.121693     4.2
29           Laptop Cooling Pad      990        0.150794     4.3
30                Action Camera     2100        0.444444     4.6
31               Smart Doorbell     1750        0.351852     4.5
32              Streaming Stick     2500        0.550265     4.4
33           Portable Projector     1450        0.272487     4.6
34                 Gaming Chair     2100        0.444444     4.7
35               Desk Organizer      450        0.007937     4.1
36              USB Flash Drive      900        0.126984     4.2
37       Phone Screen Protector      600        0.047619     4.0
38                Laptop Sleeve      720        0.079365     4.3
39           Wireless Presenter      520        0.026455     4.4
40         Tablet Keyboard Case      850        0.113757     4.5
41             Smart Thermostat     1200        0.206349     4.6
42              Security Camera     2100        0.444444     4.4
43                 Drone Camera     1800        0.365079     4.7
44              Electric Kettle     1400        0.259259     4.3
45                    Air Fryer     2200        0.470899     4.6
46                 Robot Vacuum     1650        0.325397     4.5
47                  Smart Scale      980        0.148148     4.4
48          Digital Photo Frame      870        0.119048     4.3
49                 Portable Fan      760        0.089947     4.2

    Rating_MinMax  Reviews  Reviews_MinMax
0        0.428571     1520        0.291005
1        0.714286      980        0.148148
2        0.142857      870        0.119048
3        0.857143     2100        0.444444
4        0.571429     3050        0.695767
5        0.285714     1750        0.351852
6        0.000000      620        0.052910
7        0.428571     1120        0.185185
8        1.000000     1850        0.378307
9        0.285714      760        0.089947
10       0.857143     4200        1.000000
11       0.714286     2100        0.444444
12       0.571429     1300        0.232804
13       0.142857      540        0.031746
14       0.285714      870        0.119048
15       0.857143     2300        0.497354
16       0.428571      760        0.089947
17       0.571429     1600        0.312169
18       0.714286     3500        0.814815
19       0.428571      980        0.148148
20       0.000000      420        0.000000
21       0.571429     1450        0.272487
22       0.857143     1250        0.219577
23       0.285714      720        0.079365
24       0.714286     2100        0.444444
25       0.571429      980        0.148148
26       1.000000     3100        0.708995
27       0.428571     1300        0.232804
28       0.285714      880        0.121693
29       0.428571      990        0.150794
30       0.857143     2100        0.444444
31       0.714286     1750        0.351852
32       0.571429     2500        0.550265
33       0.857143     1450        0.272487
34       1.000000     2100        0.444444
35       0.142857      450        0.007937
36       0.285714      900        0.126984
37       0.000000      600        0.047619
38       0.428571      720        0.079365
39       0.571429      520        0.026455
40       0.714286      850        0.113757
41       0.857143     1200        0.206349
42       0.571429     2100        0.444444
43       1.000000     1800        0.365079
44       0.428571     1400        0.259259
45       0.857143     2200        0.470899
46       0.714286     1650        0.325397
47       0.571429      980        0.148148
48       0.428571      870        0.119048
49       0.285714      760        0.089947

In [13]:
# 2. Z-Score normalisation
df['Units_Sold_zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()

print('\nZ-Score Normalised Units_Sold:\n')
print(df[['Product_Name','Units_Sold','Units_Sold_zscore']])

Z-Score Normalised Units_Sold:

                   Product_Name  Units_Sold  Units_Sold_zscore
0                Wireless Mouse         350           0.812282
1             Bluetooth Speaker         220          -0.260855
2                  USB Keyboard         180          -0.591051
3                Gaming Headset         410           1.307576
4                    Smartwatch         520           2.215615
5                    Power Bank         390           1.142478
6                  Laptop Stand         140          -0.921247
7                        Webcam         260           0.069341
8                  Portable SSD         330           0.647184
9              Wireless Charger         190          -0.508502
10  Noise Cancelling Headphones         610           2.958556
11          Mechanical Keyboard         290           0.316988
12                 Gaming Mouse         340           0.729733
13                 Tablet Stand         120          -1.086345
14                      USB Hub         200          -0.425953
15          External Hard Drive         310           0.482086
16            Smartphone Tripod         210          -0.343404
17              Laptop Backpack         420           1.390125
18            Bluetooth Earbuds         530           2.298164
19                LED Desk Lamp         260           0.069341
20                 Phone Holder         150          -0.838698
21            Wireless Keyboard         310           0.482086
22             Portable Monitor         170          -0.673600
23                   Smart Plug         210          -0.343404
24                  WiFi Router         390           1.142478
25              Graphics Tablet         160          -0.756149
26                   VR Headset         140          -0.921247
27                   Microphone         270           0.151890
28             Smart Light Bulb         240          -0.095757
29           Laptop Cooling Pad         260           0.069341
30                Action Camera         200          -0.425953
31               Smart Doorbell         180          -0.591051
32              Streaming Stick         430           1.472674
33           Portable Projector         120          -1.086345
34                 Gaming Chair          90          -1.333992
35               Desk Organizer         160          -0.756149
36              USB Flash Drive         320           0.564635
37       Phone Screen Protector         380           1.059929
38                Laptop Sleeve         210          -0.343404
39           Wireless Presenter         130          -1.003796
40         Tablet Keyboard Case         150          -0.838698
41             Smart Thermostat         110          -1.168894
42              Security Camera         260           0.069341
43                 Drone Camera          70          -1.499090
44              Electric Kettle         310           0.482086
45                    Air Fryer         200          -0.425953
46                 Robot Vacuum         120          -1.086345
47                  Smart Scale         170          -0.673600
48          Digital Photo Frame         150          -0.838698
49                 Portable Fan         240          -0.095757

In [14]:
# 3. Decimal-Scaling
df['Price_decimal'] = df['Price'] / 100000

print('\nDecimal Scaled Price:\n')
print(df[['Product_Name','Price','Price_decimal']])

Decimal Scaled Price:

                   Product_Name  Price  Price_decimal
0                Wireless Mouse    799        0.00799
1             Bluetooth Speaker   1499        0.01499
2                  USB Keyboard    699        0.00699
3                Gaming Headset   2499        0.02499
4                    Smartwatch   3999        0.03999
5                    Power Bank   1199        0.01199
6                  Laptop Stand    899        0.00899
7                        Webcam   1899        0.01899
8                  Portable SSD   5499        0.05499
9              Wireless Charger    999        0.00999
10  Noise Cancelling Headphones   7999        0.07999
11          Mechanical Keyboard   4599        0.04599
12                 Gaming Mouse   1599        0.01599
13                 Tablet Stand    699        0.00699
14                      USB Hub    899        0.00899
15          External Hard Drive   6499        0.06499
16            Smartphone Tripod   1199        0.01199
17              Laptop Backpack   1999        0.01999
18            Bluetooth Earbuds   2999        0.02999
19                LED Desk Lamp   1299        0.01299
20                 Phone Holder    499        0.00499
21            Wireless Keyboard   2499        0.02499
22             Portable Monitor   8999        0.08999
23                   Smart Plug    799        0.00799
24                  WiFi Router   3499        0.03499
25              Graphics Tablet   4599        0.04599
26                   VR Headset  12999        0.12999
27                   Microphone   2199        0.02199
28             Smart Light Bulb    699        0.00699
29           Laptop Cooling Pad   1499        0.01499
30                Action Camera   9999        0.09999
31               Smart Doorbell   5999        0.05999
32              Streaming Stick   3499        0.03499
33           Portable Projector  11999        0.11999
34                 Gaming Chair  15999        0.15999
35               Desk Organizer    599        0.00599
36              USB Flash Drive    799        0.00799
37       Phone Screen Protector    299        0.00299
38                Laptop Sleeve    999        0.00999
39           Wireless Presenter   1499        0.01499
40         Tablet Keyboard Case   2999        0.02999
41             Smart Thermostat  10999        0.10999
42              Security Camera   4999        0.04999
43                 Drone Camera  24999        0.24999
44              Electric Kettle   1999        0.01999
45                    Air Fryer   7999        0.07999
46                 Robot Vacuum  18999        0.18999
47                  Smart Scale   2499        0.02499
48          Digital Photo Frame   3499        0.03499
49                 Portable Fan    999        0.00999

# PART 2: Turning categorical variables into quantitative variables in python

In [15]:
import pandas as pd
import numpy as np

data = {
    'order_id': [101,102,103,104,105,106],
    'gender':['male','female','female','male','female','male'],
    'payment_method':['upi','credit card','debit card','cod','upi', ' debit card'],
    'payment_category':['electronics','clothing','home','electronics','beauty','electronics'],
    'city':['pune','mumbai','delhi','bangalore','pune','hyderabad'],
    'order_value':[1528,2956,3652,2842,5962,4587]
}


df = pd.DataFrame(data)
print(df)

   order_id  gender payment_method payment_category       city  order_value
0       101    male            upi      electronics       pune         1528
1       102  female    credit card         clothing     mumbai         2956
2       103  female     debit card             home      delhi         3652
3       104    male            cod      electronics  bangalore         2842
4       105  female            upi           beauty       pune         5962
5       106    male     debit card      electronics  hyderabad         4587

In [16]:
# Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['gender_encoded'] = le.fit_transform(df['gender'])
df

,order_id,gender,payment_method,payment_category,city,order_value,gender_encoded
0,101,male,upi,electronics,pune,1528,1
1,102,female,credit card,clothing,mumbai,2956,0
2,103,female,debit card,home,delhi,3652,0
3,104,male,cod,electronics,bangalore,2842,1
4,105,female,upi,beauty,pune,5962,0
5,106,male,debit card,electronics,hyderabad,4587,1

In [17]:
# Method 2: One-Hot encoding
df_encoded = pd.get_dummies(df, columns=['payment_method'])

print(df_encoded)

   order_id  gender payment_category       city  order_value  gender_encoded  \
0       101    male      electronics       pune         1528               1
1       102  female         clothing     mumbai         2956               0
2       103  female             home      delhi         3652               0
3       104    male      electronics  bangalore         2842               1
4       105  female           beauty       pune         5962               0
5       106    male      electronics  hyderabad         4587               1

   payment_method_ debit card  payment_method_cod  payment_method_credit card  \
0                       False               False                       False
1                       False               False                        True
2                       False               False                       False
3                       False                True                       False
4                       False               False                       False
5                        True               False                       False

   payment_method_debit card  payment_method_upi
0                      False                True
1                      False               False
2                       True               False
3                      False               False
4                      False                True
5                      False               False

In [18]:
# Encoding Multiple Columns
df_multi = pd.get_dummies(df, columns=['payment_method','payment_category','city'])

print(df_multi)

   order_id  gender  order_value  gender_encoded  payment_method_ debit card  \
0       101    male         1528               1                       False
1       102  female         2956               0                       False
2       103  female         3652               0                       False
3       104    male         2842               1                       False
4       105  female         5962               0                       False
5       106    male         4587               1                        True

   payment_method_cod  payment_method_credit card  payment_method_debit card  \
0               False                       False                      False
1               False                        True                      False
2               False                       False                       True
3                True                       False                      False
4               False                       False                      False
5               False                       False                      False

   payment_method_upi  payment_category_beauty  payment_category_clothing  \
0                True                    False                      False
1               False                    False                       True
2               False                    False                      False
3               False                    False                      False
4                True                     True                      False
5               False                    False                      False

   payment_category_electronics  payment_category_home  city_bangalore  \
0                          True                  False           False
1                         False                  False           False
2                         False                   True           False
3                          True                  False            True
4                         False                  False           False
5                          True                  False           False

   city_delhi  city_hyderabad  city_mumbai  city_pune
0       False           False        False       True
1       False           False         True      False
2        True           False        False      False
3       False           False        False      False
4       False           False        False       True
5       False            True        False      False

In [19]:
# Method 3: Dummy Enconding (Drop First)
df_dummy = pd.get_dummies(df, columns=['payment_method'], drop_first=True)

print(df_dummy)

   order_id  gender payment_category       city  order_value  gender_encoded  \
0       101    male      electronics       pune         1528               1
1       102  female         clothing     mumbai         2956               0
2       103  female             home      delhi         3652               0
3       104    male      electronics  bangalore         2842               1
4       105  female           beauty       pune         5962               0
5       106    male      electronics  hyderabad         4587               1

   payment_method_cod  payment_method_credit card  payment_method_debit card  \
0               False                       False                      False
1               False                        True                      False
2               False                       False                       True
3                True                       False                      False
4               False                       False                      False
5               False                       False                      False

   payment_method_upi
0                True
1               False
2               False
3               False
4                True
5               False

In [20]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/Student-Dataset.csv')
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [21]:
# Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender_encoded'] = le.fit_transform(df['Gender'])
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_encoded
0,101,Female,Computer,8.2,0,92,Placed,450000,0
1,102,Male,IT,7.5,1,85,Not Placed,0,1
2,103,Female,ENTC,9.1,0,96,Placed,550000,0
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,1
4,105,Female,Computer,8.7,0,88,Placed,480000,0
5,106,Male,Civil,7.2,3,72,Not Placed,0,1
6,107,Female,IT,8.9,0,91,Placed,500000,0
7,108,Male,Computer,6.5,1,80,Not Placed,0,1
8,109,Female,ENTC,7.8,0,84,Placed,420000,0
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,1

In [22]:
# Method 2: One-Hot encoding
df_encoded = pd.get_dummies(df, columns=['Attendance_Percentage'])

print(df_encoded)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs Placement_Status  \
0      101  Female    Computer   8.2                   0           Placed
1      102    Male          IT   7.5                   1       Not Placed
2      103  Female        ENTC   9.1                   0           Placed
3      104    Male  Mechanical   6.8                   2       Not Placed
4      105  Female    Computer   8.7                   0           Placed
5      106    Male       Civil   7.2                   3       Not Placed
6      107  Female          IT   8.9                   0           Placed
7      108    Male    Computer   6.5                   1       Not Placed
8      109  Female        ENTC   7.8                   0           Placed
9      110    Male  Mechanical   7.0                   2       Not Placed

   Salary  Gender_encoded  Attendance_Percentage_72  Attendance_Percentage_76  \
0  450000               0                     False                     False
1       0               1                     False                     False
2  550000               0                     False                     False
3       0               1                     False                     False
4  480000               0                     False                     False
5       0               1                      True                     False
6  500000               0                     False                     False
7       0               1                     False                     False
8  420000               0                     False                     False
9       0               1                     False                      True

   Attendance_Percentage_78  Attendance_Percentage_80  \
0                     False                     False
1                     False                     False
2                     False                     False
3                      True                     False
4                     False                     False
5                     False                     False
6                     False                     False
7                     False                      True
8                     False                     False
9                     False                     False

   Attendance_Percentage_84  Attendance_Percentage_85  \
0                     False                     False
1                     False                      True
2                     False                     False
3                     False                     False
4                     False                     False
5                     False                     False
6                     False                     False
7                     False                     False
8                      True                     False
9                     False                     False

   Attendance_Percentage_88  Attendance_Percentage_91  \
0                     False                     False
1                     False                     False
2                     False                     False
3                     False                     False
4                      True                     False
5                     False                     False
6                     False                      True
7                     False                     False
8                     False                     False
9                     False                     False

   Attendance_Percentage_92  Attendance_Percentage_96
0                      True                     False
1                     False                     False
2                     False                      True
3                     False                     False
4                     False                     False
5                     False                     False
6                     False                     False
7                     False                     False
8                     False                     False
9                     False                     False

In [23]:
# Encoding Multiple Columns
df_multi = pd.get_dummies(df, columns=['Gender','Department','Placement_Status'])

print(df_multi)

   Roll_No  CGPA  Number_of_Backlogs  Attendance_Percentage  Salary  \
0      101   8.2                   0                     92  450000
1      102   7.5                   1                     85       0
2      103   9.1                   0                     96  550000
3      104   6.8                   2                     78       0
4      105   8.7                   0                     88  480000
5      106   7.2                   3                     72       0
6      107   8.9                   0                     91  500000
7      108   6.5                   1                     80       0
8      109   7.8                   0                     84  420000
9      110   7.0                   2                     76       0

   Gender_encoded  Gender_Female  Gender_Male  Department_Civil  \
0               0           True        False             False
1               1          False         True             False
2               0           True        False             False
3               1          False         True             False
4               0           True        False             False
5               1          False         True              True
6               0           True        False             False
7               1          False         True             False
8               0           True        False             False
9               1          False         True             False

   Department_Computer  Department_ENTC  Department_IT  Department_Mechanical  \
0                 True            False          False                  False
1                False            False           True                  False
2                False             True          False                  False
3                False            False          False                   True
4                 True            False          False                  False
5                False            False          False                  False
6                False            False           True                  False
7                 True            False          False                  False
8                False             True          False                  False
9                False            False          False                   True

   Placement_Status_Not Placed  Placement_Status_Placed
0                        False                     True
1                         True                    False
2                        False                     True
3                         True                    False
4                        False                     True
5                         True                    False
6                        False                     True
7                         True                    False
8                        False                     True
9                         True                    False

In [24]:
# Method 3: Dummy Enconding (Drop First)
df_dummy = pd.get_dummies(df, columns=['Department'], drop_first=True)

print(df_dummy)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  Gender_encoded  Department_Computer  \
0           Placed  450000               0                 True
1       Not Placed       0               1                False
2           Placed  550000               0                False
3       Not Placed       0               1                False
4           Placed  480000               0                 True
5       Not Placed       0               1                False
6           Placed  500000               0                False
7       Not Placed       0               1                 True
8           Placed  420000               0                False
9       Not Placed       0               1                False

   Department_ENTC  Department_IT  Department_Mechanical
0            False          False                  False
1            False           True                  False
2             True          False                  False
3            False          False                   True
4            False          False                  False
5            False          False                  False
6            False           True                  False
7            False          False                  False
8             True          False                  False
9            False          False                   True